name: firestore_web
description:
version: 1.0.0
homepage: https://www.github.com/dartclub/firestore_dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  firestore_api:
    path: ../firestore_api

#    git:
#      url: https://github.com/dartclub/firestore_dart
#      path: firestore_api
  firebase:
    git: https://github.com/FirebaseExtended/firebase-dart

dev_dependencies:
  test: ^1.0.0