targets:
  $default:
    builders:
      firestore_serializable:
        enabled: true
        generate_for:
        - test/*
        - test/generator/*
builders:
  firestore_serializable:
    target: ":firestore_serializable"
    import: "package:firestore_serializable/firestore_serializable.dart"
    builder_factories: ["firestoreSerializer"]
    build_extensions: {".dart": [".firestore_serializable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]