name: firestore_serializable
description: ''
version: 0.0.1
homepage: https://www.github.com/dartclub/firestore_dart
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  firestore_annotations: ^0.0.1
  firestore_api:
    path: ../firestore_api
  build: '>=0.12.0 <2.0.0'  
  source_gen: ^0.9.4+7
dev_dependencies:
  build_test: ^0.10.8
  build_runner: ^1.5.0
  test: ^1.0.0
  build_verify: ^1.1.1
