name: firestore_flutter
description:
version: 0.0.1
homepage: https://www.github.com/dartclub/firestore_dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'


dependencies:
  cloud_firestore: ^0.12.9
  firestore_api:
    path: ../firestore_api
  flutter:
    sdk: flutter
  

dev_dependencies:
  test: ^1.0.0